### ISSUE TITLE
Audit Never Sent to Reporting/Analytics

### ISSUE THREAD

**Issue by MattMencel** [chef-cookbooks/audit-cis#19]
When I run my audit recipe against a node the audit runs fine and reports the failures, but the chef run fails.  I see the failed run in Chef Reporting but the actual Audit data which displays which rules have passed/failed and appears fine in /var/log/chef/client.log, never shows up in Analytics.  Unless I'm doing it wrong?

I have tried manually running audit mode from the CLI and adding it to the client.rb file.

A stacktrace from the node is below.

```
# less /var/chef/cache/chef-stacktrace.out
Generated at 2015-06-12 12:01:07 -0500
Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
1) Chef::Exceptions::AuditsFailed -  Audit phase found failures - 83/214 controls failed
/opt/chef/embedded/apps/chef/lib/chef/client.rb:373:in `run_audits'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:464:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/bin/chef-client:51:in `load'
/bin/chef-client:51:in `<main>'
```

**Comment by MattMencel** [comment]
The data is getting to the Analytics server.  I just haven't figured out how to create rules for the audit data yet.
